import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainNav } from "./components/layouts/main-nav";
import dynamic from "next/dynamic";
import StoreProvider from "@/providers/store-provider";
import { Toaster } from "./components/ui/toastet";

const AuthProvider = dynamic(() => import("@/providers/auth-provider"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <StoreProvider>
            <MainNav>{children}</MainNav>
            <Toaster />
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
